@startuml

' hide "E" circle
hide circle

' straight arrows
' skinparam linetype ortho
entity User {
  id: string
  --

  createdAt: date
  deletedAt?: date
}

entity AuthLoginLink {
  id: string
  --

  userId: User
  createdAt: date
  activatedAt?: date
  expireAt: date
}
AuthLoginLink }o--|| User

@enduml