@startuml

' hide "E" circle
hide circle

' straight arrows
' skinparam linetype ortho
entity User {
  userId: autoincrement
  --
  nickName: string
  firstName?: string
  lastName?: string

  role: Role
  userSubscription?: Subscription
  userSubscriptionHistory?: SubscriptionHistory

  createdAt: date
  deletedAt?: date
}

note left of User::role
  type Role = 'user' | 'admin'
end note

note left of User::userSubscription
  type Subscription =
    | NoneSubscription
    | Tier1Subscription
    | Tier2Subscription

  type NoneSubscription = {
    tpe: 'NoneSubscription'
  }

  type Tier1Subscription = {
    tpe: 'Tier1Subscription'
  }

  type Tier2Subscription = {
    tpe: 'Tier1Subscription'
  }
end note

note left of User::userSubscriptionHistory
  type SubscriptionHistory = {
    entries: SubscriptionHistoryEntry[]
  }

  type SubscriptionHistoryEntry = {
    subscription: Subscription
    timestamp: Date
  }
end note

@enduml