---
- name: Add Docker Group
  group:
    name: "docker"
    state: present

- name: "Adding {{ ansible_user }} to group docker"
  user:
    name: "{{ ansible_user }}"
    groups:
      - "docker"
    append: true

- name: Add Docker Signing Key
  apt_key:
    state: present
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: Add Docker Repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: "docker"

- name: Install Docker
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: present
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  register: docker_install

- name: Restart service # noqa 503
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
  when: docker_install.changed

- name: Check current docker-compose version
  command: "{{ docker_compose_path }} --version"
  register: docker_compose_current_version
  check_mode: false
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different
  ansible.builtin.file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: 'u+x,g+x'
  when: >
    docker_compose_current_version.stdout is not defined
    or docker_compose_version not in docker_compose_current_version.stdout
