---
- hosts: "{{ target | default('all') }}"
  user: "{{ ansible_user }}"
  become: true

  roles:
    - hostname
    - common
    - docker
    - security
    - nginx_prod
    - nginx_jenkins
    - nginx_nexus
    - certbot