---
- name: Register email
  vars:
    email: kazancevstepan0@gmail.com
  shell: |
    certbot -n register --agree-tos --email {{ email }}
    touch /etc/letsencrypt/.registered
  args:
    creates: /etc/letsencrypt/.registered

- name: Setup cronjob for renewal
  cron:
    name: certbot-renewal
    job: "/bin/bash -lc '/usr/local/bin/certbot -q renew'"
    minute: "0"
    hour: "14"

- name: Get certificate frontend
  vars:
    frontend_domain_name: support-chat.vsquad.ru
  command: certbot -n --nginx -d {{ frontend_domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ frontend_domain_name }}
  ignore_errors: true

- name: Get certificate backend
  vars:
    backend_domain_name: support-chat-api.vsquad.ru
  command: certbot -n --nginx -d {{ backend_domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ backend_domain_name }}
  ignore_errors: true

- name: Get certificate jenkins
  vars:
    jenkins_domain_name: jenkins.vsquad.ru
  command: certbot -n --nginx -d {{ jenkins_domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ jenkins_domain_name }}
  ignore_errors: true

- name: Get certificate nexus
  vars:
    nexus_domain_name: nexus.vsquad.ru
  command: certbot -n --nginx -d {{ nexus_domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ nexus_domain_name }}
  ignore_errors: true
