---
- name: Prune old images and unused volumes
  community.docker.docker_prune:
    volumes: true
    images: true
    images_filters:
      dangling: false

- name: Prune dangling images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: true
